runtime: java17

instance_class: F4_1G

env_variables:
    POSTGRES_USER : ${POSTGRES_USER}
    POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    POSTGRES_DB : ${POSTGRES_DB}
    NGROK_URI: ${NGROK_URI}
    JDBC_DATABASE_URL: ${JDBC_URL}
    GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    GITHUB_CLIENT_ID_TESTS: ${GITHUB_CLIENT_ID_TESTS}
    GITHUB_CLIENT_SECRET_TESTS: ${GITHUB_CLIENT_SECRET_TESTS}
    CLASSCODE_ENCRYPTION_KEY: ${CLASSCODE_ENCRYPTION_KEY}
    SENDGRID_CLASSCODE_API_KEY: ${SENDGRID_CLASSCODE_API_KEY}
