FROM postgres

USER postgres
WORKDIR /app

COPY code/jvm/sql/create.sql /docker-entrypoint-initdb.d/create.sql
COPY code/jvm/sql/triggerRequests.sql /docker-entrypoint-initdb.d/triggerRequests.sql

COPY --chown=postgres:postgres ./docker/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432