FROM postgres

USER postgres
WORKDIR /app

COPY code/jvm/sql/createTables.sql /docker-entrypoint-initdb.d/createTables.sql
COPY code/jvm/sql/triggers.sql /docker-entrypoint-initdb.d/triggers.sql

COPY --chown=postgres:postgres ./docker/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432