FROM node:10-alpine as builder

COPY ./code/js/package.json ./code/js/package-lock.json ./
RUN npm install && mkdir /react-ui && mv ./node_modules ./react-ui
WORKDIR /react-ui
COPY /code/js .
RUN npm run build


FROM nginx

COPY ./code/jvm/docker/nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /react-ui/public /usr/share/nginx/html


