FROM openjdk:17
ARG DEPENDENCY=./code/jvm/build/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.isel.leic.ps.ionClassCode.IonClassCodeApplicationKt"]
