FROM postgres:latest

USER postgres
WORKDIR /app

COPY ./code/sql/createTables.sql /docker-entrypoint-initdb.d/1_create.sql
COPY ./code/sql/triggers.sql /docker-entrypoint-initdb.d/2_triggers.sql

COPY --chown=postgres:postgres ./code/jvm/docker/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

# Expose PostgreSQL default port
EXPOSE 5432
