version: "3.9"
services:

  # The service running the API
  spring-service:
    hostname: spring-service
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-Spring
    environment:
      PORT: 8080
      NGROK_URI: ${NGROK_URI}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CLIENT_ID_TESTS: ${GITHUB_CLIENT_ID_TESTS}
      GITHUB_CLIENT_SECRET_TESTS: ${GITHUB_CLIENT_SECRET_TESTS}
      CLASSCODE_ENCRYPTION_KEY: ${CLASSCODE_ENCRYPTION_KEY}
      SENDGRID_CLASSCODE_API_KEY: ${SENDGRID_CLASSCODE_API_KEY}

    ports:
      - "8080:8080"

  # The service running the load-balancer
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/dhparams:/etc/nginx/dhparams
      - /etc/letsencrypt/live/classcode.i-on.live:/etc/letsencrypt/live/classcode.i-on.live
      - /etc/letsencrypt/archive/classcode.i-on.live:/etc/letsencrypt/archive/classcode.i-on.live

    depends_on:
      - spring-service
