version: "3.9"
services:
  # The service running the DB
  db-docker:
    container_name: db-docker
    hostname: db-docker
    build:
        context: ../..
        dockerfile: code/jvm/docker/files/Dockerfile-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"

  # The service running the API
  spring-service:
    hostname: spring-service
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-Spring
    environment:
      PORT: 8081
      NGROK_URI: ${NGROK_URI}
      JDBC_DATABASE_URL: jdbc:postgresql://db-docker:5432/classcode?user=postgres&password=Qasdf2010!
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CLIENT_ID_TESTS: ${GITHUB_CLIENT_ID_TESTS}
      GITHUB_CLIENT_SECRET_TESTS: ${GITHUB_CLIENT_SECRET_TESTS}
      CLASSCODE_ENCRYPTION_KEY: ${CLASSCODE_ENCRYPTION_KEY}
      SENDGRID_CLASSCODE_API_KEY: ${SENDGRID_CLASSCODE_API_KEY}

    ports:
      - "8080"

    depends_on:
      - db-docker

  # The service running the load-balancer
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-nginx
    environment:
      NGROK_URI: ${NGROK_URI}
    ports:
      - "3000:3000"

    depends_on:
      - spring-service


