version: "3.9"
services:

  # The service running the API
  spring-service:
    hostname: spring-service
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-Spring
    environment:
      PORT: 8081
      NGROK_URI: ${NGROK_URI}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CLIENT_ID_TESTS: ${GITHUB_CLIENT_ID_TESTS}
      GITHUB_CLIENT_SECRET_TESTS: ${GITHUB_CLIENT_SECRET_TESTS}
      CLASSCODE_ENCRYPTION_KEY: ${CLASSCODE_ENCRYPTION_KEY}
      SENDGRID_CLASSCODE_API_KEY: ${SENDGRID_CLASSCODE_API_KEY}

    ports:
      - "8080"

  # The service running the load-balancer
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-nginx
    ports:
      - "443:3000"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - spring-service

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ricardo.freitas.henriques@gmail.com --agree-tos --no-eff-email -d classcode.i-on-live

