version: "3.9"
services:
  # The service running the DB
  db-docker:
    container_name: db-docker
    hostname: db-docker
    build:
        context: ../..
        dockerfile: code/jvm/docker/files/Dockerfile-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5555:5432"

  spring-service:
    container_name: spring-service
    hostname: spring-service
    build:
      context: ../..
      dockerfile: code/jvm/docker/files/Dockerfile-Spring
    environment:
      PORT: 8081
      JDBC_DATABASE_URL: ${JDBC_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      CLASSCODE_ENCRYPTION_KEY: ${CLASSCODE_ENCRYPTION_KEY}
      SENDGRID_CLASSCODE_API_KEY: ${SENDGRID_CLASSCODE_API_KEY}

    ports:
      - "8081:8080"

    depends_on:
      - db-docker

  # The service running the load-balancer
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx:/etc/nginx
    depends_on:
      - spring-service


